[[library]]
type="lib"
name="v8"
includes=[
  "include/libplatform/libplatform-export.h",
  "include/libplatform/libplatform.h",
  "include/libplatform/v8-tracing.h",
  "include/v8-inspector-protocol.h",
  "include/v8-inspector.h",
  "include/v8-platform.h",
  "include/v8-profiler.h",
  "include/v8-testing.h",
  "include/v8-util.h",
  "include/v8-value-serializer-version.h",
  "include/v8-version-string.h",
  "include/v8-version.h",
  "include/v8.h",
  "include/v8config.h"
]
incdirs=["/usr/include/nodejs/deps/v8", "/usr/include/nodejs/deps/v8/include"]

[[library]]
type="lib"
name="ircclient"
includes=["libirc_errors.h", "libirc_events.h", "libirc_options.h", "libirc_rfcnumeric.h", "libircclient.h"]

[[library]]
type="git"
name="sdlpp"
path="https://github.com/mika314/sdlpp.git"
includes=["sdlpp/sdlpp.hpp"]

[[library]]
type="pkgconfig"
name="sdl2"
includes=["SDL.h"]

[[library]]
type="pkgconfig"
name="SDL2_ttf"
includes=["SDL_ttf.h"]

[[library]]
type="pkgconfig"
name="SDL2_image"
includes=["SDL_image.h"]

[[library]]
type="pkgconfig"
name="fftw3"
includes=["fftw3.h"]

[[library]]
type="pkgconfig"
name="libswscale"
includes=["libswscale/swscale.h"]

[[library]]
type="pkgconfig"
name="libavformat"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavutil"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavcodec"
includes=["libavformat/avformat.h"]

[[library]]
type="pkgconfig"
name="libavdevice"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libavutil"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libavcodec"
includes=["libavdevice/avdevice.h"]

[[library]]
type="pkgconfig"
name="libcurl"
includes=["curl/curl.h"]

[[library]]
type="pkgconfig"
name="libpulse"
includes=["pulse/thread-mainloop.h", "pulse/context.h", "pulse/stream.h", "pulse/scache.h"]

[[library]]
type="pkgconfig"
name="gsl"
includes=["gsl/gsl_fit.h"]

[[library]]
type="pkgconfig"
name="jsoncpp"
includes=["json/json.h"]

[[library]]
type="lib"
name="glut"
includes=["GL/glut.h"]

[[library]]
type="pkgconfig"
name="libuv"
includes=["uv.h"]

[[library]]
type="lib"
name="GL"
includes=["SDL_opengl.h", "GL/glut.h"]

[[library]]
type="git"
name="cpptoml"
path="https://github.com/skystrife/cpptoml.git"
includes=["cpptoml.h"]
incdir="include"

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="pkgconfig"
name="libtomcrypt"
includes=["tomcrypt.h"]

[[library]]
type="pkgconfig"
name="libpulse-simple"
includes=["pulse/simple.h"]

[[library]]
type="pkgconfig"
name="libpulse"
includes=["pulse/simple.h"]

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="git"
name="catch2"
version="v2.x"
path="https://github.com/catchorg/Catch2.git"
includes=["catch2/catch.hpp"]
incdir="single_include"

[[library]]
type="git"
name="easy_draw"
path="https://github.com/mika314/easy-draw.git"
includes=[
  "easy_draw/easy_draw.hpp"
]

# file repos WIP

[[library]]
type="git"
name="shade"
path="https://github.com/mika314/shade.git"
includes=[
  "shade/array_buffer.hpp",
  "shade/gl_check_error.hpp",
  "shade/obj.hpp",
  "shade/shader_program.hpp",
  "shade/var.hpp",
  "shade/library.hpp"
]

[[library]]
type="git"
name="log"
includes=["log/log.hpp"]
path="https://github.com/mika314/log.git"

[[library]]
type="git"
name="coeff"
includes=["coeff/coeff.hpp", "coeff/coeff_reg.hpp"]
path="https://github.com/mika314/coeff.git"

[[library]]
type="pkgconfig"
name="hiredis"
includes=["hiredis/hiredis.h"]

[[library]]
type="pkgconfig"
name="zlib"
includes=["zlib.h"]

[[library]]
type="pkgconfig"
name="glew"
includes=["GL/glew.h"]

[[library]]
type="git"
name="ser"
version="main"
path="https://github.com/mika314/ser.git"
includes=[
  "ser/is_serializable.hpp",
  "ser/istrm.hpp",
  "ser/macro.hpp",
  "ser/ostrm.hpp",
  "ser/overloaded.hpp",
  "ser/proto.hpp",
  "ser/schema.hpp",
  "ser/ser.hpp",
]
