[[library]]
type="git"
name="sdlpp"
path="https://github.com/mika314/sdlpp.git"
includes=["sdlpp/sdlpp.hpp"]

[[library]]
type="pkgconfig"
name="sdl2"
includes=["SDL.h", "SDL2/SDL.h"]

[[library]]
type="pkgconfig"
name="SDL2_ttf"
includes=["SDL_ttf.h", "SDL2/SDL_ttf.h"]

[[library]]
type="pkgconfig"
name="SDL2_mixer"
includes=["SDL_mixer.h", "SDL2/SDL_mixer.h"]

[[library]]
type="pkgconfig"
name="SDL2_image"
includes=["SDL_image.h", "SDL2/SDL_image.h"]

[[library]]
type="pkgconfig"
name="SDL2_net"
includes=["SDL_net.h", "SDL2/SDL_net.h"]

[[library]]
type="lib"
name="Ws2_32"
includes=["Winsock2.h"]

[[library]]
type="pkgconfig"
name="jsoncpp"
includes=["json/json.h"]

[[library]]
type="lib"
name="glut"
includes=["GL/glut.h"]

[[library]]
type="pkgconfig"
name="libuv"
includes=["uv.h"]

[[library]]
type="lib"
name="GL"
includes=["SDL_opengl.h", "GL/glut.h", "SDL2/SDL_opengl.h"]

[[library]]
type="git"
name="cpptoml"
path="https://github.com/mika314/cpptoml.git"
includes=["cpptoml.h"]
incdir="include"

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="git"
name="fastnoise"
path="https://github.com/Auburns/FastNoise.git"
includes=["fastnoise/FastNoise.h"]

[[library]]
type="git"
name="catch2"
path="https://github.com/catchorg/Catch2.git"
includes=["catch2/catch.hpp"]
incdir="single_include"

[[library]]
type="git"
name="easy_draw"
path="https://github.com/mika314/easy-draw.git"
includes=[
  "easy_draw/easy_draw.hpp"
]

# file repos WIP

[[library]]
type="git"
name="shade"
path="https://github.com/mika314/shade.git"
includes=[
  "shade/array_buffer.hpp",
  "shade/gl_check_error.hpp",
  "shade/obj.hpp",
  "shade/shader_program.hpp",
  "shade/texture_library.hpp",
  "shade/var.hpp"
]

[[library]]
type="git"
name="log"
includes=["log/log.hpp"]
path="https://github.com/mika314/log.git"

[[library]]
type="git"
name="coeff"
includes=["coeff/coeff.hpp", "coeff/coeff_reg.hpp"]
path="https://github.com/mika314/coeff.git"

[[library]]
type="git"
name="ser"
version="main"
path="https://github.com/mika314/ser.git"
includes=[
  "ser/is_serializable.hpp",
  "ser/istrm.hpp",
  "ser/macro.hpp",
  "ser/ostrm.hpp",
  "ser/overloaded.hpp",
  "ser/proto.hpp",
  "ser/schema.hpp",
  "ser/ser.hpp",
]

[[library]]
type="git"
version="main"
name="json"
path="https://github.com/mika314/json.git"
includes=["json/json.hpp"]

[[library]]
type="git"
name="glm"
path="https://github.com/g-truc/glm.git"
includes=["glm/common.hpp",
          "glm/exponential.hpp",
          "glm/ext.hpp",
          "glm/fwd.hpp",
          "glm/geometric.hpp",
          "glm/glm.hpp",
          "glm/integer.hpp",
          "glm/mat2x2.hpp",
          "glm/mat2x3.hpp",
          "glm/mat2x4.hpp",
          "glm/mat3x2.hpp",
          "glm/mat3x3.hpp",
          "glm/mat3x4.hpp",
          "glm/mat4x2.hpp",
          "glm/mat4x3.hpp",
          "glm/mat4x4.hpp",
          "glm/matrix.hpp",
          "glm/packing.hpp",
          "glm/trigonometric.hpp",
          "glm/vec2.hpp",
          "glm/vec3.hpp",
          "glm/vec4.hpp",
          "glm/vector_relational.hpp"]
incdir="."

[[library]]
type="git"
version="master"
name="stb"
path="https://github.com/nothings/stb.git"
includes=["stb/stb_c_lexer.h",
          "stb/stb_connected_components.h",
          "stb/stb_divide.h",
          "stb/stb_ds.h",
          "stb/stb_dxt.h",
          "stb/stb_easy_font.h",
          "stb/stb_herringbone_wang_tile.h",
          "stb/stb_hexwave.h",
          "stb/stb_image.h",
          "stb/stb_image_resize.h",
          "stb/stb_image_write.h",
          "stb/stb_include.h",
          "stb/stb_leakcheck.h",
          "stb/stb_perlin.h",
          "stb/stb_rect_pack.h",
          "stb/stb_sprintf.h",
          "stb/stb_textedit.h",
          "stb/stb_tilemap_editor.h",
          "stb/stb_truetype.h",
          "stb/stb_voxel_render.h"]

[[library]]
type="pkgconfig"
name="libcurl"
includes=["curl/curl.h"]

[[library]]
type="lib"
name="tomcrypt"
dependencies=["tommath"]
includes=["tomcrypt.h"]

[[library]]
type="lib"
name="tommath"
includes=["tommath.h"]

[[library]]
type="pkgconfig"
name="assimp"
includes=[
  "assimp/Base64.hpp",
  "assimp/BaseImporter.h",
  "assimp/Bitmap.h",
  "assimp/BlobIOSystem.h",
  "assimp/ByteSwapper.h",
  "assimp/ColladaMetaData.h",
  "assimp/Compiler",
  "assimp/Compiler/poppack1.h",
  "assimp/Compiler/pstdint.h",
  "assimp/Compiler/pushpack1.h",
  "assimp/CreateAnimMesh.h",
  "assimp/DefaultIOStream.h",
  "assimp/DefaultIOSystem.h",
  "assimp/DefaultLogger.hpp",
  "assimp/Exceptional.h",
  "assimp/Exporter.hpp",
  "assimp/GenericProperty.h",
  "assimp/GltfMaterial.h",
  "assimp/Hash.h",
  "assimp/IOStream.hpp",
  "assimp/IOStreamBuffer.h",
  "assimp/IOSystem.hpp",
  "assimp/Importer.hpp",
  "assimp/LineSplitter.h",
  "assimp/LogAux.h",
  "assimp/LogStream.hpp",
  "assimp/Logger.hpp",
  "assimp/MathFunctions.h",
  "assimp/MemoryIOWrapper.h",
  "assimp/NullLogger.hpp",
  "assimp/ParsingUtils.h",
  "assimp/Profiler.h",
  "assimp/ProgressHandler.hpp",
  "assimp/RemoveComments.h",
  "assimp/SGSpatialSort.h",
  "assimp/SceneCombiner.h",
  "assimp/SkeletonMeshBuilder.h",
  "assimp/SmallVector.h",
  "assimp/SmoothingGroups.h",
  "assimp/SmoothingGroups.inl",
  "assimp/SpatialSort.h",
  "assimp/StandardShapes.h",
  "assimp/StreamReader.h",
  "assimp/StreamWriter.h",
  "assimp/StringComparison.h",
  "assimp/StringUtils.h",
  "assimp/Subdivision.h",
  "assimp/TinyFormatter.h",
  "assimp/Vertex.h",
  "assimp/XMLTools.h",
  "assimp/XmlParser.h",
  "assimp/ZipArchiveIOSystem.h",
  "assimp/aabb.h",
  "assimp/ai_assert.h",
  "assimp/anim.h",
  "assimp/camera.h",
  "assimp/cexport.h",
  "assimp/cfileio.h",
  "assimp/cimport.h",
  "assimp/color4.h",
  "assimp/color4.inl",
  "assimp/commonMetaData.h",
  "assimp/config.h",
  "assimp/defs.h",
  "assimp/fast_atof.h",
  "assimp/importerdesc.h",
  "assimp/light.h",
  "assimp/material.h",
  "assimp/material.inl",
  "assimp/matrix3x3.h",
  "assimp/matrix3x3.inl",
  "assimp/matrix4x4.h",
  "assimp/matrix4x4.inl",
  "assimp/mesh.h",
  "assimp/metadata.h",
  "assimp/pbrmaterial.h",
  "assimp/postprocess.h",
  "assimp/qnan.h",
  "assimp/quaternion.h",
  "assimp/quaternion.inl",
  "assimp/scene.h",
  "assimp/texture.h",
  "assimp/types.h",
  "assimp/vector2.h",
  "assimp/vector2.inl",
  "assimp/vector3.h",
  "assimp/vector3.inl",
  "assimp/version.h"]
